pub const MAX_EXTERNAL_RETRY_ATTEMPTS: usize = 3;
pub const MAX_NOTIFICATION_RETRY_ATTEMPTS: i32 = 3;
pub const NOTIFICATION_RETRY_DELAY_SECONDS: i64 = 60;
pub const CIRCUIT_BREAKER_FAILURE_THRESHOLD: u32 = 5;
pub const CIRCUIT_BREAKER_OPEN_SECONDS: u64 = 60;
pub const PENDING_NOTIFICATION_BATCH_SIZE: i64 = 25;
