pub const DEFAULT_HTTP_TIMEOUT_SECONDS: u64 = 15;
pub const GEMINI_TIMEOUT_SECONDS: u64 = 30;
pub const GOOGLE_SHEETS_TIMEOUT_SECONDS: u64 = 20;
pub const OPENAI_TRANSCRIPTION_TIMEOUT_SECONDS: u64 = 60;
pub const TELEGRAM_SEND_TIMEOUT_SECONDS: u64 = 10;
pub const DATABASE_CONNECT_TIMEOUT_SECONDS: u64 = 5;
