use std::collections::HashSet;
use std::env;
use std::num::NonZeroU32;

use secrecy::SecretString;
use serde::Serialize;
use serde_json::json;
use validator::Validate;

use crate::domain::errors::{AppError, AppResult};

const DEFAULT_GEMINI_MODEL: &str = "gemini-2.5-flash";
const DEFAULT_RATE_LIMIT_PER_MINUTE: u32 = 20;
const DEFAULT_OPENAI_TRANSCRIPTION_MODEL: &str = "gpt-4o-mini-transcribe";
const DEFAULT_BIND_ADDRESS: &str = "0.0.0.0:8080";
const DEFAULT_LOG_LEVEL: &str = "info,telegram_task_bot=debug";

#[derive(Debug, Clone, Validate, Serialize)]
pub struct AppConfig {
    pub database: DatabaseConfig,
    pub telegram: TelegramConfig,
    pub google_sheets: GoogleSheetsConfig,
    pub gemini: GeminiConfig,
    pub openai: OpenAiConfig,
    pub http_server: HttpServerConfig,
    pub observability: ObservabilityConfig,
    pub scheduler: SchedulerConfig,
    pub bot: BotBehaviorConfig,
    pub security: SecurityConfig,
    pub features: FeatureFlagsConfig,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct DatabaseConfig {
    #[validate(length(min = 1))]
    pub database_url: String,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct TelegramConfig {
    #[serde(skip_serializing)]
    pub bot_token: SecretString,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct GoogleSheetsConfig {
    #[validate(length(min = 1))]
    pub spreadsheet_id: String,
    #[validate(length(min = 1))]
    pub range: String,
    #[serde(skip_serializing)]
    pub api_key: Option<SecretString>,
    #[serde(skip_serializing)]
    pub bearer_token: Option<SecretString>,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct GeminiConfig {
    #[serde(skip_serializing)]
    pub api_key: SecretString,
    #[validate(length(min = 1))]
    pub model: String,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct OpenAiConfig {
    #[serde(skip_serializing)]
    pub api_key: SecretString,
    #[validate(length(min = 1))]
    pub transcription_model: String,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct HttpServerConfig {
    #[validate(length(min = 1))]
    pub bind_address: String,
}

#[derive(Debug, Clone, Validate, Serialize)]
pub struct ObservabilityConfig {
    #[validate(length(min = 1))]
    pub log_level: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct SchedulerConfig {
    pub employee_sync_interval_minutes: NonZeroU32,
    pub notification_poll_interval_seconds: NonZeroU32,
    pub reminder_tick_seconds: NonZeroU32,
    pub daily_deadline_reminder_hour_utc: u32,
    pub daily_overdue_scan_hour_utc: u32,
    pub daily_summary_hour_utc: u32,
}

#[derive(Debug, Clone, Serialize)]
pub struct BotBehaviorConfig {
    pub rate_limit_per_minute: NonZeroU32,
}

/// Security-oriented bootstrapping: which Telegram IDs become admins on
/// startup, how long admin nonces live, etc.
#[derive(Debug, Clone, Serialize)]
pub struct SecurityConfig {
    /// Bootstrap admins — the ONLY source of admin authority on a fresh DB.
    /// The set is promoted to role=Admin during startup ([phase 3]) and is
    /// also consulted as a *fallback* if every admin is demoted.
    pub admin_ids: AdminIdSet,
    /// TTL for one-time nonces generated by `AdminNonceStore` (destructive
    /// action confirmations).  Short window shrinks the replay surface.
    pub admin_nonce_ttl_seconds: NonZeroU32,
}

/// Raw ENV representation of feature flags: a CSV blob is persisted as-is so
/// that startup logs can trace exactly what the operator configured.  The
/// high-level [`FeatureFlagRegistry`] is constructed from this during
/// bootstrap ([phase 3 / 4]).
#[derive(Debug, Clone, Serialize)]
pub struct FeatureFlagsConfig {
    pub env_value: Option<String>,
}

/// Parsed `TELEGRAM_ADMIN_IDS` ENV (comma-separated).  Stays as a value
/// object instead of a bare `HashSet<i64>` so that "is this Telegram id a
/// bootstrap admin?" is a type-safe, intention-revealing call site.
#[derive(Debug, Clone, Default, Serialize)]
pub struct AdminIdSet {
    ids: HashSet<i64>,
}

impl AdminIdSet {
    pub fn new(ids: HashSet<i64>) -> Self {
        Self { ids }
    }

    pub fn is_empty(&self) -> bool {
        self.ids.is_empty()
    }

    pub fn len(&self) -> usize {
        self.ids.len()
    }

    pub fn contains(&self, telegram_id: i64) -> bool {
        self.ids.contains(&telegram_id)
    }

    pub fn iter(&self) -> impl Iterator<Item = i64> + '_ {
        self.ids.iter().copied()
    }
}

impl AppConfig {
    pub fn from_env() -> AppResult<Self> {
        dotenvy::dotenv().ok();

        let config = Self {
            database: DatabaseConfig {
                database_url: required_env("DATABASE_URL")?,
            },
            telegram: TelegramConfig {
                bot_token: SecretString::new(required_env("TELEGRAM_BOT_TOKEN")?.into()),
            },
            google_sheets: GoogleSheetsConfig {
                spreadsheet_id: required_env("GOOGLE_SHEETS_ID")?,
                range: optional_env("GOOGLE_SHEETS_RANGE")
                    .unwrap_or_else(|| "Employees!A:F".to_owned()),
                api_key: optional_secret("GOOGLE_SHEETS_API_KEY"),
                bearer_token: optional_secret("GOOGLE_SHEETS_BEARER_TOKEN"),
            },
            gemini: GeminiConfig {
                api_key: SecretString::new(required_env("GOOGLE_GEMINI_API_KEY")?.into()),
                model: optional_env("GOOGLE_GEMINI_MODEL")
                    .unwrap_or_else(|| DEFAULT_GEMINI_MODEL.to_owned()),
            },
            openai: OpenAiConfig {
                api_key: SecretString::new(required_env("OPENAI_API_KEY")?.into()),
                transcription_model: optional_env("OPENAI_TRANSCRIPTION_MODEL")
                    .unwrap_or_else(|| DEFAULT_OPENAI_TRANSCRIPTION_MODEL.to_owned()),
            },
            http_server: HttpServerConfig {
                bind_address: optional_env("BIND_ADDRESS")
                    .unwrap_or_else(|| DEFAULT_BIND_ADDRESS.to_owned()),
            },
            observability: ObservabilityConfig {
                log_level: optional_env("RUST_LOG").unwrap_or_else(|| DEFAULT_LOG_LEVEL.to_owned()),
            },
            scheduler: SchedulerConfig {
                employee_sync_interval_minutes: non_zero_u32("EMPLOYEE_SYNC_INTERVAL_MINUTES", 60)?,
                notification_poll_interval_seconds: non_zero_u32(
                    "NOTIFICATION_POLL_INTERVAL_SECONDS",
                    30,
                )?,
                reminder_tick_seconds: non_zero_u32("REMINDER_TICK_SECONDS", 60)?,
                daily_deadline_reminder_hour_utc: optional_u32("DEADLINE_REMINDER_HOUR_UTC", 9)?,
                daily_overdue_scan_hour_utc: optional_u32("OVERDUE_SCAN_HOUR_UTC", 10)?,
                daily_summary_hour_utc: optional_u32("DAILY_SUMMARY_HOUR_UTC", 8)?,
            },
            bot: BotBehaviorConfig {
                rate_limit_per_minute: non_zero_u32(
                    "RATE_LIMIT_PER_MINUTE",
                    DEFAULT_RATE_LIMIT_PER_MINUTE,
                )?,
            },
            security: SecurityConfig {
                admin_ids: parse_admin_ids(optional_env("TELEGRAM_ADMIN_IDS").as_deref())?,
                admin_nonce_ttl_seconds: non_zero_u32("ADMIN_NONCE_TTL_SECONDS", 120)?,
            },
            features: FeatureFlagsConfig {
                env_value: optional_env("FEATURE_FLAGS"),
            },
        };

        config.validate_with_rules()?;
        Ok(config)
    }

    fn validate_with_rules(&self) -> AppResult<()> {
        self.validate().map_err(|error| {
            AppError::schema_validation(
                "CONFIG_INVALID",
                "Configuration is invalid",
                json!({ "errors": error.to_string() }),
            )
        })?;

        let has_api_key = self.google_sheets.api_key.is_some();
        let has_bearer_token = self.google_sheets.bearer_token.is_some();

        if !has_api_key && !has_bearer_token {
            return Err(AppError::schema_validation(
                "GOOGLE_SHEETS_AUTH_MISSING",
                "Either GOOGLE_SHEETS_API_KEY or GOOGLE_SHEETS_BEARER_TOKEN must be configured",
                json!({ "spreadsheet_id": self.google_sheets.spreadsheet_id }),
            ));
        }

        if self.scheduler.daily_deadline_reminder_hour_utc > 23
            || self.scheduler.daily_overdue_scan_hour_utc > 23
            || self.scheduler.daily_summary_hour_utc > 23
        {
            return Err(AppError::schema_validation(
                "SCHEDULER_HOUR_INVALID",
                "Scheduler hour must be in the 0..=23 range",
                json!({
                    "deadline_hour": self.scheduler.daily_deadline_reminder_hour_utc,
                    "overdue_hour": self.scheduler.daily_overdue_scan_hour_utc,
                    "daily_summary_hour": self.scheduler.daily_summary_hour_utc,
                }),
            ));
        }

        Ok(())
    }
}

fn required_env(name: &'static str) -> AppResult<String> {
    optional_env(name).ok_or_else(|| {
        AppError::schema_validation(
            "ENV_MISSING",
            format!("Environment variable {name} is required"),
            json!({ "name": name }),
        )
    })
}

fn optional_env(name: &'static str) -> Option<String> {
    env::var(name)
        .ok()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
}

fn optional_secret(name: &'static str) -> Option<SecretString> {
    optional_env(name).map(Into::into).map(SecretString::new)
}

fn non_zero_u32(name: &'static str, default: u32) -> AppResult<NonZeroU32> {
    let value = optional_u32(name, default)?;
    NonZeroU32::new(value).ok_or_else(|| {
        AppError::schema_validation(
            "ENV_NON_ZERO_REQUIRED",
            format!("Environment variable {name} must be greater than zero"),
            json!({ "name": name, "value": value }),
        )
    })
}

fn optional_u32(name: &'static str, default: u32) -> AppResult<u32> {
    match optional_env(name) {
        Some(value) => value.parse::<u32>().map_err(|_| {
            AppError::schema_validation(
                "ENV_NUMBER_INVALID",
                format!("Environment variable {name} must be a positive integer"),
                json!({ "name": name, "value": value }),
            )
        }),
        None => Ok(default),
    }
}

fn parse_admin_ids(raw: Option<&str>) -> AppResult<AdminIdSet> {
    let Some(raw) = raw else {
        return Ok(AdminIdSet::default());
    };

    let mut ids = HashSet::new();
    for token in raw.split(',') {
        let trimmed = token.trim();
        if trimmed.is_empty() {
            continue;
        }
        let parsed = trimmed.parse::<i64>().map_err(|_| {
            AppError::schema_validation(
                "ADMIN_IDS_INVALID",
                "TELEGRAM_ADMIN_IDS must be a comma-separated list of integer Telegram user IDs",
                json!({ "token": trimmed }),
            )
        })?;
        if parsed <= 0 {
            return Err(AppError::schema_validation(
                "ADMIN_IDS_INVALID",
                "TELEGRAM_ADMIN_IDS entries must be positive Telegram user IDs",
                json!({ "token": trimmed }),
            ));
        }
        ids.insert(parsed);
    }

    Ok(AdminIdSet::new(ids))
}

#[cfg(test)]
mod tests {
    use super::parse_admin_ids;

    #[test]
    fn given_none_when_parse_admin_ids_then_returns_empty_set() {
        let set = parse_admin_ids(None).expect("none is a valid input");

        assert!(set.is_empty());
    }

    #[test]
    fn given_csv_with_whitespace_when_parse_admin_ids_then_trims_and_accepts() {
        let set = parse_admin_ids(Some(" 111 , 222,333 ")).expect("valid csv");

        assert_eq!(set.len(), 3);
        assert!(set.contains(111));
        assert!(set.contains(222));
        assert!(set.contains(333));
    }

    #[test]
    fn given_non_numeric_token_when_parse_admin_ids_then_errors() {
        let err = parse_admin_ids(Some("111,abc")).unwrap_err();

        let message = err.to_string();
        assert!(
            message.contains("ADMIN_IDS_INVALID") || message.to_lowercase().contains("admin"),
            "error should mention admin id parsing: {message}"
        );
    }

    #[test]
    fn given_negative_token_when_parse_admin_ids_then_errors() {
        let err = parse_admin_ids(Some("-42")).unwrap_err();

        let message = err.to_string();
        assert!(message.to_lowercase().contains("admin"));
    }
}
